version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/mohit-nagaraj/uptime-kuma"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "shell"